// English UI copy for the web demo. Wording mirrors the mobile app's i18n
// dictionary (single source of clinical phrasing); the engine's own output
// (component labels, warning messages) is surfaced directly.
export const strings = {
  app: {
    name: 'TPN Calculator',
    tagline: 'Configurable parenteral nutrition for neonatal & pediatric patients',
    demoBadge: 'Live demo',
    repo: 'github.com/sahinparlak/tpn-calculator',
  },
  disclaimer: {
    title: 'Before you start',
    intro:
      'TPN Calculator was built by a clinician. Its calculations follow current clinical guidance, every value is traceable to its source, and it shows safety limits clearly. The final decision is always yours.',
    chips: ['ESPGHAN 2018', 'Traceable', 'Safety'],
    profileNote:
      'Active profile: ESPGHAN 2018 reference — guideline-based, not center-validated. Verify results against your own protocol.',
    sections: [
      {
        h: 'Purpose',
        p: "An informational and educational decision-support tool for qualified healthcare professionals; it does not replace professional judgment. The engine contains no clinical constants — a result reflects the user's profile and input.",
      },
      {
        h: 'No warranty',
        p: 'The software is provided "as is"; no warranty is given, including accuracy, completeness, or fitness for a particular purpose.',
      },
      {
        h: 'Risk & responsibility on you',
        p: "Use is entirely at the user's own risk. Verifying the profile, independently checking every result, and all clinical decisions and orders are the user's responsibility.",
      },
      {
        h: 'Regulatory status',
        p: 'Not approved or registered as a medical device by any authority (FDA, EU MDR, TİTCK). Classification depends on the intended use given by the user, who is responsible for it.',
      },
    ],
    consentBefore: "I'm a qualified clinician; I accept the terms and take responsibility.",
    accept: 'I understand and accept',
    footnote: 'Full text: DISCLAIMER.md · this summary is not legal advice.',
  },
  patient: {
    title: 'Patient',
    weight: 'Weight',
    age: 'Age',
    days: 'days',
    lineType: 'Line type',
    peripheral: 'Peripheral',
    central: 'Central',
    lineHint: 'Peripheral applies stricter osmolarity / dextrose limits.',
    optional: 'Optional',
    gestationalAge: 'Gestational age',
    weeks: 'weeks',
    phototherapy: 'Phototherapy',
    radiantWarmer: 'Radiant warmer',
    fluidRestriction: 'Fluid restriction',
    errors: {
      weightPositive: 'Weight must be greater than 0.',
      ageInteger: 'Age must be a whole number of days (0 or more).',
      restrictionRange: 'Fluid restriction must be between 0 and 100.',
      gestationalRange: 'Gestational age looks out of range.',
    },
  },
  result: {
    title: 'Result',
    totalVolume: 'Total volume',
    glucose: 'Glucose',
    gir: 'GIR',
    finalDextrose: 'Final dextrose (aqueous phase)',
    amount: 'Amount',
    volume: 'Volume',
    dextroseVolume: 'Dextrose volume',
    aminoAcid: 'Amino acid',
    lipid: 'Lipid',
    electrolytes: 'Electrolytes',
    ion: 'Ion',
    total: 'total',
    additives: 'Additives',
    off: 'off',
    energy: 'Energy',
    carb: 'Carb',
    protein: 'Protein',
    fat: 'Fat',
    osmolarity: 'Osmolarity',
    osmolarityNote: 'Above the peripheral-line upper limit (clears on a central line).',
    derived: 'Derived values',
    aqueousVolume: 'Aqueous volume',
    lipidVolume: 'Lipid volume',
    caPProduct: 'Ca × P solubility product',
    caPProductNote:
      'Simplified estimate — not the classic mg²/dL² precipitation threshold. Confirm physical compatibility with your pharmacy.',
    colorKey: 'Warning color key',
    hardKey: 'red = hard / block',
    softKey: 'amber = soft / caution',
    mustNotUse: 'Must not be used without independent verification',
    hardExceeded: 'hard safety limits exceeded',
    softNote: 'soft cautions',
    noWarnings: 'No limit warnings',
    noWarningsNote: 'No hard/soft safety limits exceeded for this line. Still, verify results independently.',
    footer:
      'Clinical decision-support tool · the ordering clinician is solely responsible · verify results independently.',
    incomplete: 'Complete the patient form to see a result.',
  },
} as const;
